import { Link } from 'react-router-dom'

const categories = [['◉', 'Speakers & PA Systems', 'Clear, confident sound for any room.'], ['◌', 'Microphones', 'Reliable voice and vocal capture.'], ['✦', 'DJ Equipment', 'The tools to keep a crowd moving.'], ['▦', 'Mixing Consoles', 'Shape every channel with control.'], ['□', 'Studio Equipment', 'Focused gear for creative work.'], ['✧', 'Lighting & Effects', 'Give every moment its atmosphere.']]

const About = () => <main className="about-page">
  <section className="about-hero"><div><p className="eyebrow">● COLOMBO, SRI LANKA</p><h1>Sound moves people.<br /><em>We make it possible.</em></h1><p className="about-lead">KVAudio makes professional sound and lighting equipment easier to discover and rent for events, productions, creators and unforgettable experiences.</p><Link to="/catalogue" className="about-cta">Explore equipment&nbsp; →</Link></div><div className="about-visual"><img src="/equipment/chauvet-par.jpeg" alt="Chauvet event lighting equipment" /><img src="/soundease-hero.png" alt="Professional audio equipment" /></div></section>
  <section className="about-story"><img src="/equipment/shure-slx-wireless.jpeg" alt="Shure wireless microphone system" /><div><p className="eyebrow">OUR STORY</p><h2>Built for<br /><em>better sound.</em></h2><p>Finding reliable professional audio equipment should be simple.</p><p>KVAudio helps people discover, rent and manage the equipment they need in Colombo, from intimate gatherings and podcasts to concerts, corporate events and creative productions.</p></div></section>
  <section className="about-offer"><div className="about-section-heading"><p className="eyebrow">WHAT WE OFFER</p><h2>Everything you need<br />to be heard.</h2></div><div className="category-grid">{categories.map(([icon, title, text]) => <Link to="/catalogue" key={title} className="category-card"><span>{icon}</span><h3>{title}</h3><p>{text}</p><b>Explore equipment&nbsp; →</b></Link>)}</div></section>
  <section className="about-benefits"><p className="eyebrow">WHY KVAUDIO</p><h2>Rental, without<br /><em>the hassle.</em></h2><div className="benefit-grid">{[['01', 'Easy Booking', 'Find and reserve the equipment you need in a few steps.'], ['02', 'Professional Equipment', 'Reliable gear for events, productions and creative projects.'], ['03', 'Flexible Rentals', 'Choose rental periods that fit your schedule.'], ['04', 'Colombo Based', 'A focused platform for the local events community.']].map(([number, title, text]) => <article key={number}><strong>{number}</strong><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="about-process"><p className="eyebrow">THE PROCESS</p><h2>Simple from start<br />to sound.</h2><div className="process-grid">{[['01', 'Explore', 'Browse equipment for your event or project.'], ['02', 'Reserve', 'Choose your dates and add the right setup to your cart.'], ['03', 'Create', 'Bring your event, production or idea to life.']].map(([number, title, text]) => <article key={number}><strong>{number}</strong><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="about-mission"><p>Our mission is simple:</p><h2>Make great sound<br /><em>accessible.</em></h2><p>Professional equipment should empower creativity, not create barriers.</p></section>
</main>

export default About
