import { useEffect, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import api from '../api/axios'
import BookingStatusBadge from '../components/BookingStatusBadge'

const Bookings = () => {
  const location = useLocation(); const [bookings, setBookings] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(location.state?.message || ''); const [cancelTarget, setCancelTarget] = useState(null); const [processing, setProcessing] = useState(false)
  useEffect(() => { api.get('/bookings/my-bookings').then(({ data }) => setBookings(data.bookings)).catch((e) => setError(e.response?.data?.message || 'Unable to load bookings.')).finally(() => setLoading(false)) }, [])
  const cancel = async () => { setProcessing(true); try { const { data } = await api.patch(`/bookings/${cancelTarget._id}/cancel`); setBookings((all) => all.map((b) => b._id === data.booking._id ? data.booking : b)); setSuccess(`${data.booking.service} was cancelled successfully.`); setCancelTarget(null) } catch (e) { setError(e.response?.data?.message || 'Unable to cancel booking.') } finally { setProcessing(false) } }
  return <main className="editorial-page editorial-bookings"><div className="editorial-page-heading"><div><p className="eyebrow">SOUNDEASE / RENTALS</p><h1>My bookings</h1><p>View and manage your equipment reservations.</p></div><Link to="/bookings/create" className="editorial-action">Create booking</Link></div>{success && <p className="editorial-message success">{success}</p>}{error && <p className="editorial-message error">{error}</p>}<div className="editorial-table-wrap">{loading ? <p className="editorial-empty">Loading bookings...</p> : bookings.length === 0 ? <p className="editorial-empty">No bookings found.</p> : <table><thead><tr>{['Equipment','Date','Time','Status','Notes','Created','Actions'].map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{bookings.map((b) => <tr key={b._id}><td><strong>{b.service}</strong></td><td>{new Date(b.date).toLocaleDateString()}</td><td>{b.startTime} – {b.endTime}</td><td><BookingStatusBadge status={b.status} /></td><td>{b.notes || '—'}</td><td>{new Date(b.createdAt).toLocaleDateString()}</td><td>{!['completed', 'cancelled'].includes(b.status) && <button type="button" onClick={() => setCancelTarget(b)} className="editorial-danger">Cancel</button>}</td></tr>)}</tbody></table>}</div>{cancelTarget && <div className="editorial-modal"><section role="alertdialog"><h2>Cancel booking?</h2><p>Are you sure you want to cancel this booking?</p><div><button type="button" disabled={processing} onClick={() => setCancelTarget(null)} className="editorial-secondary">Keep booking</button><button type="button" disabled={processing} onClick={cancel} className="editorial-danger">{processing ? 'Cancelling...' : 'Cancel booking'}</button></div></section></div>}</main>
}
export default Bookings
