import { useEffect, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import api from '../api/axios'
import BookingStatusBadge from '../components/BookingStatusBadge'

const Bookings = () => {
  const location = useLocation(); const [bookings, setBookings] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(location.state?.message || ''); const [cancelTarget, setCancelTarget] = useState(null); const [processing, setProcessing] = useState(false)
  useEffect(() => { api.get('/bookings/my-bookings').then(({ data }) => setBookings(data.bookings)).catch((e) => setError(e.response?.data?.message || 'Unable to load bookings.')).finally(() => setLoading(false)) }, [])
  const cancel = async () => { setProcessing(true); try { const { data } = await api.patch(`/bookings/${cancelTarget._id}/cancel`); setBookings((all) => all.map((b) => b._id === data.booking._id ? data.booking : b)); setSuccess(`${data.booking.service} was cancelled successfully.`); setCancelTarget(null) } catch (e) { setError(e.response?.data?.message || 'Unable to cancel booking.') } finally { setProcessing(false) } }
  return <main className="mx-auto w-full max-w-6xl px-6 py-12"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-wider text-blue-700">Bookings</p><h1 className="mt-2 text-3xl font-bold text-slate-900">My Bookings</h1><p className="mt-2 text-slate-600">View and manage your reservations.</p></div><Link to="/bookings/create" className="rounded-lg bg-blue-700 px-4 py-2.5 text-center font-semibold text-white">Create Booking</Link></div>{success && <p className="mt-6 rounded-lg bg-emerald-50 p-4 text-sm text-emerald-700">{success}</p>}{error && <p className="mt-6 rounded-lg bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="mt-8 overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm">{loading ? <p className="p-8 text-center text-slate-600">Loading bookings...</p> : bookings.length === 0 ? <p className="p-8 text-center text-slate-600">No bookings found.</p> : <table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Service','Date','Time','Status','Notes','Created','Actions'].map((h) => <th key={h} className="px-5 py-4">{h}</th>)}</tr></thead><tbody className="divide-y">{bookings.map((b) => <tr key={b._id}><td className="px-5 py-4 font-medium">{b.service}</td><td className="px-5 py-4">{new Date(b.date).toLocaleDateString()}</td><td className="px-5 py-4">{b.startTime} – {b.endTime}</td><td className="px-5 py-4"><BookingStatusBadge status={b.status} /></td><td className="max-w-xs px-5 py-4 text-slate-600">{b.notes || '—'}</td><td className="px-5 py-4">{new Date(b.createdAt).toLocaleDateString()}</td><td className="px-5 py-4">{!['completed', 'cancelled'].includes(b.status) && <button type="button" onClick={() => setCancelTarget(b)} className="font-semibold text-red-700">Cancel Booking</button>}</td></tr>)}</tbody></table>}</div>{cancelTarget && <div className="fixed inset-0 z-20 flex items-center justify-center bg-slate-900/40 px-6"><section role="alertdialog" className="w-full max-w-md rounded-2xl bg-white p-7 shadow-xl"><h2 className="text-2xl font-bold">Cancel Booking?</h2><p className="mt-4 text-slate-700">Are you sure you want to cancel this booking?</p><div className="mt-7 flex justify-end gap-3"><button type="button" disabled={processing} onClick={() => setCancelTarget(null)} className="rounded-lg border px-4 py-2 font-semibold">Keep Booking</button><button type="button" disabled={processing} onClick={cancel} className="rounded-lg bg-red-700 px-4 py-2 font-semibold text-white disabled:opacity-50">{processing ? 'Cancelling...' : 'Cancel Booking'}</button></div></section></div>}</main>
}
export default Bookings
