import { useEffect, useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import equipment from '../data/equipment'
import { useCart } from '../context/CartContext'

const FilterDropdown = ({ label, value, options, onChange }) => { const [open, setOpen] = useState(false); const selectableOptions = options.filter((option) => option.value !== 'All' && option.value !== 'featured'); return <div className="filter-dropdown"><button type="button" className="field filter-dropdown-trigger" onClick={() => setOpen(!open)} aria-expanded={open}>{value === 'All' || value === 'featured' ? label : options.find((option) => option.value === value)?.label || value}<span>⌄</span></button>{open && <div className="filter-dropdown-menu">{selectableOptions.map((option) => <button type="button" key={option.value} className={option.value === value ? 'selected' : ''} onClick={() => { onChange(option.value); setOpen(false) }}>{option.label}</button>)}</div>}</div> }

const Catalogue = () => { const [params, setParams] = useSearchParams(); const { addToCart, cartItems } = useCart(); const [query, setQuery] = useState(params.get('search') || ''); const category = params.get('category') || 'All'; const brand = params.get('brand') || 'All'; const sort = params.get('sort') || 'featured'; const [filtersOpen, setFiltersOpen] = useState(false); const categories = ['All', ...new Set(equipment.map((item) => item.category))]; const brands = ['All', ...new Set(equipment.map((item) => item.brand))]; useEffect(() => { const timer = setTimeout(() => { const next = new URLSearchParams(params); if (query) next.set('search', query); else next.delete('search'); setParams(next, { replace: true }) }, 350); return () => clearTimeout(timer) }, [query])
  const setFilter = (key, value) => { const next = new URLSearchParams(params); if (value === 'All' || value === 'featured') next.delete(key); else next.set(key, value); setParams(next) }; const clear = () => { setQuery(''); setParams({}) }; const filtered = useMemo(() => { const q = query.toLowerCase(); const result = equipment.filter((item) => `${item.name} ${item.brand} ${item.model} ${item.category}`.toLowerCase().includes(q) && (category === 'All' || item.category === category) && (brand === 'All' || item.brand === brand)); return [...result].sort((a, b) => sort === 'price-low' ? a.pricePerDay - b.pricePerDay : sort === 'price-high' ? b.pricePerDay - a.pricePerDay : sort === 'rating' ? b.rating - a.rating : sort === 'name-az' ? a.name.localeCompare(b.name) : sort === 'name-za' ? b.name.localeCompare(a.name) : 0) }, [query, category, brand, sort])
  const FilterPanel = () => <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><FilterDropdown label="Category" value={category} options={[{ value: 'All', label: 'Category' }, ...categories.filter((item) => item !== 'All').map((item) => ({ value: item, label: item }))]} onChange={(value) => setFilter('category', value)} /><FilterDropdown label="Brand" value={brand} options={[{ value: 'All', label: 'Brand' }, ...brands.filter((item) => item !== 'All').map((item) => ({ value: item, label: item }))]} onChange={(value) => setFilter('brand', value)} /><FilterDropdown label="Sort by" value={sort} options={[{ value: 'featured', label: 'Sort by' }, { value: 'price-low', label: 'Price: Low to High' }, { value: 'price-high', label: 'Price: High to Low' }, { value: 'rating', label: 'Highest Rated' }, { value: 'name-az', label: 'Name: A-Z' }, { value: 'name-za', label: 'Name: Z-A' }]} onChange={(value) => setFilter('sort', value)} /></div>
  return <main className="mx-auto w-full max-w-7xl px-5 py-12 sm:px-6"><div className="text-center"><p className="text-sm font-bold uppercase tracking-wider text-amber-600">KVAudio · Colombo</p><h1 className="mt-2 text-4xl font-bold text-slate-900">Audio Equipment Catalogue</h1><p className="mx-auto mt-3 max-w-2xl text-slate-600">Choose the right sound, lighting and staging setup for your event.</p></div><div className="mt-10 flex flex-col gap-3 sm:flex-row"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search equipment, brand, model..." className="field flex-1" /><button type="button" onClick={() => setFiltersOpen(!filtersOpen)} className="rounded-lg border border-slate-300 px-4 py-2 font-semibold lg:hidden">{filtersOpen ? 'Hide Filters' : 'Show Filters'}</button><button type="button" onClick={clear} className="rounded-lg border border-slate-300 px-4 py-2 font-semibold">Clear Filters</button></div><div className={`${filtersOpen ? 'block' : 'hidden'} mt-4 rounded-xl border border-slate-200 bg-white p-4 lg:block`}><FilterPanel /></div><div className="mt-12 flex items-center justify-between"><h2 className="text-2xl font-bold text-slate-900">Equipment</h2><p className="text-sm text-slate-600">{filtered.length} items found</p></div>{filtered.length ? <div className="mt-5 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((item) => { const inCart = cartItems.some((entry) => entry.id === item.id); return <article key={item.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="bg-slate-100 p-4"><img src={item.image} alt={`${item.brand} ${item.name}`} className="h-52 w-full object-cover" /></div><div className="p-5"><div className="flex justify-between text-sm"><span className="font-semibold text-blue-700">{item.category}</span><span className={item.available ? 'text-emerald-600' : 'text-red-600'}>{item.available ? 'Available' : 'Unavailable'}</span></div><h3 className="mt-2 text-xl font-bold">{item.name}</h3><p className="text-sm text-slate-500">{item.brand} · {item.subcategory}</p><p className="mt-2 text-sm text-slate-600">★ {item.rating} · {item.location}</p><div className="mt-4 flex items-center justify-between"><strong>Rs. {item.pricePerDay.toLocaleString()} / day</strong><button type="button" disabled={!item.available || inCart} onClick={() => addToCart(item)} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white disabled:bg-slate-300">{inCart ? 'In Cart' : 'Add'}</button></div><Link to={`/catalogue/${item.id}`} className="mt-3 block text-center text-sm font-semibold text-blue-700">Equipment Details</Link></div></article> })}</div> : <div className="mt-6 rounded-xl bg-white p-12 text-center text-slate-600">No equipment matches your filters.</div>}</main>
}
export default Catalogue
